$(function(){"use strict"
function t(){function t(){var t=$(".vert-slider-bar li div").index(this)
o=t,i.children().stop().animate({top:n*t*-1},1e3),s.find("li").eq(o).addClass("active").siblings().removeClass("active")}function e(){o+=1,o>=i.children().children().children().length&&(o=0),s.find("li div").eq(o).trigger("click")}var a,s=$(".vert-slider-bar"),i=$(".vert-slider-contents"),n=i.height(),o=0
s.find("li").first().addClass("active"),s.find("li div").on("click",t),a=setInterval(e,5e3),$(".vert-slider").on("mouseenter",function(){clearInterval(a)}).on("mouseleave",function(){a=setInterval(e,5e3)})}function e(){var t=$(".archive-section .accord-info")
t.on("click",function(){$(this).toggleClass("not-opn opn").next().slideToggle().parents(".accord-wrap").find(t).not(this).removeClass("opn").addClass("not-opn"),$(".accord-content").not($(this).next()).slideUp()}).addClass("not-opn").first().removeClass("not-opn").addClass("opn"),$(".archive-section .post-date").on("click",function(){$(this).toggleClass("not-opn opn").next().slideToggle()}).addClass("not-opn").first().removeClass("not-opn").addClass("opn")}function a(){var t,e=$(".ticker ul"),a=0,s=$(".ticker").width(),i=0
e.each(function(){function n(){i-=1,i<-e.width()&&(i=s),e.css("left",i+"px")}e.children("li").length>=1&&($(this).children("li").each(function(t,e){a+=$(e).outerWidth(!0)}),$(this).width(a+1)),t=setInterval(n,12),e.on("mouseenter",function(){clearInterval(t)}).on("mouseleave",function(){t=setInterval(n,12)})})}var s=$("body > div"),i="js_plugins",n="js_plugins_caro",o=$(".post-share-butt i"),l="mov-left",r=$("[id*='-color']"),c=!1
s.hasClass(i)&&$(".main-content, .sidebar-content").theiaStickySidebar({additionalMarginTop:40}),$('input[type="submit"]').on("click",function(t){t.preventDefault()
var e=$('input[type="email"]'),a="error-input"
$(this).parents("form").find(e).toggleClass(a),$(e).hasClass(a)?$(e).val($(e).val()+" < Error Message Here!"):$(e).val(" ")}),$(".search-bar i").on("click",function(t){t.preventDefault()
var e="shw_inpt",a="shw_inpt_2"
return $(this).hasClass(e)?$(this).next().animate({width:"0",padding:"0"},400).parents(".top-bar").find(".social-bar").css("margin-left","0"):$(this).hasClass(a)?$(this).next().animate({width:"190px",padding:"0 20px"},400).parents(".top-bar").find(".social-bar").css("margin-left","-13.5%"):$(this).next().animate({width:"190px",padding:"0 20px"},400).parents(".top-bar").find(".social-bar").css("margin-left","-18%"),$(this).toggleClass(e),!1}),$(".accounts-wrap").on("click",function(){$(".accounts").fadeToggle("fast")}),o.on("click",function(){$(this).toggleClass(l).parent().next().fadeToggle(350).parents(".post-img").on("mouseleave",function(){o.removeClass(l).parent().next().fadeOut()})}),s.hasClass(i)&&$(".intr-slid").bxSlider({mode:"vertical",slideMargin:5,pager:!1,auto:!0,autoHover:!0,pause:6e3}),s.hasClass(i)&&$(".intr-slid-preview_1").bxSlider({mode:"horizontal",slideMargin:5,pager:!1,auto:!0,autoHover:!0,pause:4e3,speed:800}),$("head").append('<link rel="stylesheet" href="#default-style">','<link rel="stylesheet" href="#main-color">'),$(".style i").on("click",function(){$(this).siblings("div").fadeToggle("fast")}),$(".skin").on("click",function(){$(this).hasClass("dark")?$("link[href*='default-style']").attr("href","css/colorize/dark-style.css"):($("link[href*='dark']").attr("href","#default-style"),$("link[href*='colorize']").attr("href","#main-color"),r.removeClass("star"))}),r.on("click",function(){$(this).addClass("star").siblings().removeClass("star"),$("link[href*='-color']").attr("href","css/colorize/"+$(this).attr("id")+".css")}),s.hasClass(i)&&$("#caro-slider").owlCarousel({autoplay:!0,autoplayTimeout:5e3,autoplayHoverPause:!0,loop:!0,margin:20,nav:!1,responsive:{0:{items:1},544:{items:2},768:{items:3}}}),$(".section6 .tab-bar a:first").addClass("active"),$(".section6 .tab-content .menu:not(:first)").hide(),$(".section6 .tab-bar a").on("click",function(){var t=$(this).attr("href")
return $(this).addClass("active").parent().siblings().find("a").removeClass("active"),$(t).fadeIn(500).siblings().hide(),!1}),s.hasClass(i)&&($("#fad-slider").owlCarousel({items:1,animateOut:"fadeOut",autoplay:!0,autoplayTimeout:5e3,autoplayHoverPause:!0,loop:!0,margin:15,nav:!0,navText:[""],dots:!1,smartSpeed:700}),$(".section8 .opti").on("click",function(){var t=$(".section8 .caption"),e=$(".caption-open"),a=$(".caption-close")
$(this).hasClass("caption-open")?t.animate({bottom:"0"},250,function(){e.fadeOut("fast"),a.show().parent().prev().css("top","-180px")}):t.animate({bottom:"-100%"},250,function(){e.fadeIn(),a.hide().parent().prev().css("top","0")})})),t(),s.hasClass(i)&&$("#popular-section").owlCarousel({items:1,autoplay:!0,autoplayTimeout:5e3,autoplayHoverPause:!0,loop:!0,margin:20,nav:!1,smartSpeed:700}),e(),a(),$(".scroll-top").on("click",function(){$("html, body").animate({scrollTop:0},1500)}),$(".sitemap .accord .title").on("click",function(){$(this).toggleClass("not-opn opn").next().slideToggle(500)}).first().addClass("opn").parent().siblings().find(".title").addClass("not-opn"),$(".account .checkbox input").on("click",function(){$(this).toggleClass("check-ico")}),$(".forgot-pass").on("click",function(t){t.preventDefault()
var e=$(".forgot")
e.show().find(".form-close").on("click",function(){e.hide()})}),s.hasClass(n)&&$("[class*='-sidebar'] #caro-slider").owlCarousel({autoplay:!0,autoplayTimeout:5e3,autoplayHoverPause:!0,loop:!0,margin:20,nav:!1,responsive:{0:{items:1},480:{items:2},768:{items:3}}}),$(".post-option .txt-siz span").on("click",function(){var t=$(".post-body > p")
!c&&$(this).hasClass("incr-font")?(c=!0,$(t).animate({fontSize:"+=1px"}),setTimeout(function(){c=!1},1e3),"24px"===$(t).css("font-size")&&$(t).animate().stop()):!c&&$(this).hasClass("decr-font")&&(c=!0,$(t).animate({fontSize:"-=1px"}),setTimeout(function(){c=!1},1e3),"17px"===$(t).css("font-size")&&$(t).animate().stop())}),$(".post-option .prnt span").on("click",function(){return window.print(),!1}),$("#sendToMail").on("click",function(){var t=window.location.href,e=$(".post-head > .post-title").text()
$(this).attr("href",'mailto:?&subject=MESH MAG New Article&body=Hi my friend,,, You can read a new article "'+e+'" at this link '+t)}),s.hasClass(n)&&$(".post-fullwidth #caro-slider").owlCarousel({autoplay:!0,autoplayTimeout:5e3,autoplayHoverPause:!0,loop:!0,margin:20,nav:!1,responsive:{0:{items:1},480:{items:2},768:{items:3},1e3:{items:4}}}),$(".comments .bar li a[href='#site']").addClass("active"),$(".comments .comm:not(#site)").hide(),$(".comments .bar li a").on("click",function(){var t=$(this).attr("href")
return $(this).addClass("active").parent().siblings().find("a").removeClass("active"),$(t).fadeIn(500).siblings().hide(),!1}),$(".nav-respon-butt").on("click",function(){$(this).next(".nav-bar").fadeToggle()}),$(".menu-respon-butt").on("click",function(){$(this).toggleClass("shw_arw").next(".menu").fadeToggle()})})
